name: Node.js CI

on: [push, pull_request]

jobs:
  build-frontend:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Install, test and lint webapp
      working-directory: ./webapp
      run: |
        npm install
        npm run test:unit
        npm run lint
      env:
        CI: true

  build-backend:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - uses: KarakoA/setup-neo4j@v1.1.1
      with:
        tag: '4.2.1'
        passwort: password
    - name: Install, test and lint backend
      working-directory: ./backend
      run: |
        npm install
        npm run test
        npm run lint
      env:
        CI: true,
        JWTSECRET: ${{ secrets.JWTSECRET }},
        NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
        NEO4J_URI: ${{ secrets.NEO4J_URI }}
        NEO4J_USER: ${{ secrets.NEO4J_USER }}
