name: Node.js CI

on: [push, pull_request]

jobs:
  build-frontend:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Install, test and lint webapp
      working-directory: ./webapp
      run: |
        npm install
        npm run test:unit
        npm run lint
      env:
        CI: true

  build-backend:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Install, test and lint backend
      working-directory: ./backend
      run: |
        touch .env
        echo JWTSECRET=githubactions >> .env
        npm install
        npm run test
        npm run lint
      env:
        CI: true
